import { Basin } from './types';

export const BASINS: Basin[] = [
  {
    id: 'meric-ergene',
    name: 'Meriç-Ergene',
    nameTr: 'Meriç-Ergene Havzası',
    lat: 41.67,
    lng: 26.56,
    zoom: 8,
    countries: ['Türkiye', 'Yunanistan', 'Bulgaristan'],
    rivers: ['Meriç (Evros/Maritsa)', 'Tunca', 'Arda', 'Ergene'],
    worldBankCountryCode: 'TR',
    openMeteoLat: 41.67,
    openMeteoLng: 26.56,
    floodLat: 41.67,
    floodLng: 26.56,
    rssKeywords: ['Meriç', 'Evros', 'Maritsa', 'Edirne taşkın'],
    dsiLinks: [
      { title: 'DSİ Meriç Havzası Verileri', url: 'https://www.dsi.gov.tr' },
      { title: 'MGMM Edirne İstasyonu', url: 'https://www.mgm.gov.tr' },
    ],
    synthesis: 'Meriç-Ergene havzası, Türkiye-Yunanistan-Bulgaristan arasında paylaşılan kritik bir sınıraşan su sistemidir. Meriç Nehri, yıllık ortalama 7.4 milyar m³ akışla bölgenin en önemli su kaynağıdır. İklim değişikliği senaryoları, 2050 yılına kadar %15-25 arası debi azalması öngörmektedir. Taşkın riski özellikle kış ve ilkbahar aylarında yüksektir.',
  },
  {
    id: 'firat-dicle',
    name: 'Fırat-Dicle',
    nameTr: 'Fırat-Dicle Havzası',
    lat: 37.95,
    lng: 40.23,
    zoom: 6,
    countries: ['Türkiye', 'Suriye', 'Irak'],
    rivers: ['Fırat (Euphrates)', 'Dicle (Tigris)', 'Habur', 'Büyük Zap'],
    worldBankCountryCode: 'TR',
    openMeteoLat: 37.95,
    openMeteoLng: 40.23,
    floodLat: 37.95,
    floodLng: 40.23,
    rssKeywords: ['Fırat', 'Dicle', 'Euphrates', 'Tigris', 'GAP', 'baraj'],
    dsiLinks: [
      { title: 'DSİ GAP Bölgesi Verileri', url: 'https://www.dsi.gov.tr' },
      { title: 'GAP İdaresi İstatistikleri', url: 'https://www.gap.gov.tr' },
    ],
    synthesis: 'Fırat-Dicle sistemi, Orta Doğu\'nun en stratejik su kaynağıdır. Türkiye\'nin GAP projesi kapsamında 22 baraj ve 19 HES inşa edilmiştir. Fırat\'ın yıllık ortalama debisi ~30 milyar m³, Dicle\'nin ise ~21 milyar m³\'tür. Su paylaşımı, bölgesel jeopolitiğin en kritik unsurlarından biridir.',
  },
  {
    id: 'aras-kura',
    name: 'Aras-Kura',
    nameTr: 'Aras-Kura Havzası',
    lat: 40.2,
    lng: 43.95,
    zoom: 7,
    countries: ['Türkiye', 'Gürcistan', 'Ermenistan', 'Azerbaycan', 'İran'],
    rivers: ['Aras (Araxes)', 'Kura (Mtkvari)', 'Arpaçay', 'Çoruh'],
    worldBankCountryCode: 'TR',
    openMeteoLat: 40.2,
    openMeteoLng: 43.95,
    floodLat: 40.2,
    floodLng: 43.95,
    rssKeywords: ['Aras', 'Kura', 'Kafkasya su', 'Arpaçay'],
    dsiLinks: [
      { title: 'DSİ Doğu Anadolu Verileri', url: 'https://www.dsi.gov.tr' },
    ],
    synthesis: 'Aras-Kura havzası, Güney Kafkasya\'nın en karmaşık sınıraşan su sistemidir. Beş ülke arasında paylaşılan bu havzada, siyasi gerilimler su yönetimini zorlaştırmaktadır. Aras Nehri\'nin yıllık debisi ~10 milyar m³ olup, iklim değişikliği ve buzul erimesi akış rejimini değiştirmektedir.',
  },
  {
    id: 'asi',
    name: 'Asi (Orontes)',
    nameTr: 'Asi (Orontes) Havzası',
    lat: 36.2,
    lng: 36.15,
    zoom: 8,
    countries: ['Türkiye', 'Suriye', 'Lübnan'],
    rivers: ['Asi (Orontes)', 'Afrin', 'Karasu'],
    worldBankCountryCode: 'TR',
    openMeteoLat: 36.2,
    openMeteoLng: 36.15,
    floodLat: 36.2,
    floodLng: 36.15,
    rssKeywords: ['Asi nehri', 'Orontes', 'Hatay su', 'Amik'],
    dsiLinks: [
      { title: 'DSİ Hatay Bölge Verileri', url: 'https://www.dsi.gov.tr' },
    ],
    synthesis: 'Asi (Orontes) Nehri, Lübnan\'dan doğup Suriye üzerinden Türkiye\'ye ulaşan ters akışlı bir nehirdir. Yıllık ortalama debisi ~2.5 milyar m³\'tür. Suriye iç savaşı sonrası su altyapısının tahribatı, havzadaki su güvenliğini ciddi şekilde etkilemiştir.',
  },
];

export const DEFAULT_BLR: import('./types').BLRParams = {
  government: 0.5,
  energy: 0.5,
  population: 0.5,
  foodWater: 0.5,
  health: 0.5,
  communication: 0.5,
  transportation: 0.5,
};
